name: onic_esports_app
description: "A management app for ONIC Esports fans."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  device_info_plus: ^10.1.0
  webview_flutter: ^4.8.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0

  # LIBRARY BARU UNTUK STATE MANAGEMENT
  provider: ^6.1.2

  go_router: ^14.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

    # Pastikan baris ini ada
  flutter_bloc: ^8.1.5  # Gunakan versi terbaru jika memungkinkan

    # Pastikan baris ini ada
  equatable: ^2.0.5   # Gunakan versi terbaru jika memungkinkan

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/